# Generated by Django 3.2.4 on 2021-06-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('postalcode', models.IntegerField(max_length=100)),
                ('phoneprimary', models.IntegerField(max_length=100)),
                ('phonesecondary', models.IntegerField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=105)),
                ('lastname', models.CharField(max_length=105)),
                ('fullname', models.CharField(max_length=210)),
                ('countryid', models.IntegerField()),
                ('phonenumber', models.IntegerField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AddField(
            model_name='address',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
