# Generated by Django 3.2.4 on 2021-06-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210624_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Id',
            new_name='id',
        ),
    ]
